---
title: "O-Well Assignment #1"
author: "Cassidy Zehner [cassidy.zehner]"
output: html_notebook
---
# Setup Folder Structure
```{r}
which.github = "remote";  # local ... remote 

github.local = "C:/_git_/github/CassidyZehner/WSU_STATS419_2021/";
github.remote = "https://raw.githubusercontent.com/CassidyZehner/WSU_STATS419_2021/main/";

#https://raw.githubusercontent.com/CassidyZehner/WSU_STATS419_2021/main/workspace/o-well/data/well.txt

if(which.github == "remote")
  {
  mypath = paste0(github.remote,"/workspace/o-well/")
  # include.me = paste0( github.remote, "functions/functions-intro.R");
  # library(devtools);
  # source_url(include.me);
  } else {
          mypath= paste0(github.local,"/workspace/o-well/")
          # include.me = paste0( github.local, "functions/functions-intro.R");
          # source(include.me);
          }
```

# Read in Data
(explain)
```{r}
path.data = paste0(mypath, "data/")
owell.metals = read.delim(paste0(path.data,"table1.txt"),header=TRUE,sep="");
owell.chemistry = read.delim(paste0(path.data,"table2.txt"),header=TRUE,sep="");
well.location = read.delim(paste0(path.data,"wells-location.txt"),header=TRUE,sep="|");
```

#Build one data object
(explain)
```{r}
owell.metals$latitude = well.location$latitude;
owell.metals$longitude = well.location$longitude;
owell.metals$altitude.ft = well.location$altitude.ft;
owell.metals$fault = well.location$fault;
owell.metals$geology = well.location$geology;

owell.chemistry$latitude = well.location$latitude;
owell.chemistry$longitude = well.location$longitude;
owell.chemistry$altitude.ft = well.location$altitude.ft;
owell.chemistry$fault = well.location$fault;
owell.chemistry$geology = well.location$geology;
#?merge
wells = list();
	wells$saudi = list();
	wells$saudi$metals = owell.metals;
	wells$saudi$chemistry = owell.chemistry

# mylist = list(owell.chemistry,owell.metals)
# names(mylist) = c("wells$saudi$chemistry","wells$saudi$metals")
```

```{r}
storeToPipe = function(df, file, header=TRUE, quote="", sep="|", row.names=FALSE)
  {
  if(quote == "") { quote = FALSE; }
  utils::write.table(df, file=file, quote=quote, col.names=header, row.names=row.names, sep=sep);
  }

readFromPipe = function(file, header=TRUE, quote="", sep="|")
  {
  utils::read.csv(file, header=header, quote=quote, sep=sep);
  }
```

# Save data list to file
```{r}
if(which.github != "remote")
{
myfile = paste0(path.data,"well.rds")
saveRDS(wells,file = myfile)
myfile = paste0(path.data,"well.txt")
storeToPipe(wells,file = myfile)
} else {
 myfile = paste0(path.data,"well.txt")
 print(myfile)
}

```

